// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"database/sql"
)

type Datasource struct {
	ID        string
	Name      string
	CreatedAt int64
}

type Document struct {
	ID           string
	DatasourceID string
	Title        string
	Description  sql.NullString
	CreatedAt    int64
}

type TextChunk struct {
	ID         string
	DocumentID string
	Content    string
	CreatedAt  int64
}

type TextEmbedding struct {
	ID          string
	ModelID     string
	TextChunkID string
	Vector      []byte
	CreatedAt   int64
}
