// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

type Document struct {
	ID          string
	Title       string
	Description string
	Data        string
	CreatedAt   int64
}

type TextChunk struct {
	ID         string
	DocumentID string
	Content    string
	SegContent string
	CreatedAt  int64
}

type TextChunkFt struct {
	ID         string
	SegContent string
}

type TextEmbedding struct {
	ModelID     string
	TextChunkID string
	Vector      []byte
	CreatedAt   int64
}
