// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dao

import (
	"context"
	"database/sql"
)

const deleteDatasource = `-- name: DeleteDatasource :exec
DELETE
FROM datasource
WHERE id = ?
`

func (q *Queries) DeleteDatasource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDatasource, id)
	return err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE
FROM document
WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const deleteTextChunk = `-- name: DeleteTextChunk :exec
DELETE
FROM text_chunk
WHERE id = ?
`

func (q *Queries) DeleteTextChunk(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTextChunk, id)
	return err
}

const getDatasource = `-- name: GetDatasource :one
SELECT id, name, created_at
FROM datasource
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDatasource(ctx context.Context, id string) (Datasource, error) {
	row := q.db.QueryRowContext(ctx, getDatasource, id)
	var i Datasource
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, datasource_id, title, description, created_at
FROM document
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DatasourceID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTextChunk = `-- name: GetTextChunk :one
SELECT id, document_id, content, created_at
FROM text_chunk
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTextChunk(ctx context.Context, id string) (TextChunk, error) {
	row := q.db.QueryRowContext(ctx, getTextChunk, id)
	var i TextChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listDatasources = `-- name: ListDatasources :many
SELECT id, name, created_at
FROM datasource
`

func (q *Queries) ListDatasources(ctx context.Context) ([]Datasource, error) {
	rows, err := q.db.QueryContext(ctx, listDatasources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datasource
	for rows.Next() {
		var i Datasource
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextChunksByDocumentID = `-- name: ListTextChunksByDocumentID :many
SELECT id, document_id, content, created_at
FROM text_chunk
WHERE document_id = ?
`

func (q *Queries) ListTextChunksByDocumentID(ctx context.Context, documentID string) ([]TextChunk, error) {
	rows, err := q.db.QueryContext(ctx, listTextChunksByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TextChunk
	for rows.Next() {
		var i TextChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newDatasource = `-- name: NewDatasource :one
INSERT INTO datasource (id, name)
VALUES (?, ?)
RETURNING id, name, created_at
`

type NewDatasourceParams struct {
	ID   string
	Name string
}

func (q *Queries) NewDatasource(ctx context.Context, arg NewDatasourceParams) (Datasource, error) {
	row := q.db.QueryRowContext(ctx, newDatasource, arg.ID, arg.Name)
	var i Datasource
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const newDocument = `-- name: NewDocument :one
INSERT INTO document (id, datasource_id, title, description)
VALUES (?, ?, ?, ?)
RETURNING id, datasource_id, title, description, created_at
`

type NewDocumentParams struct {
	ID           string
	DatasourceID string
	Title        string
	Description  sql.NullString
}

func (q *Queries) NewDocument(ctx context.Context, arg NewDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, newDocument,
		arg.ID,
		arg.DatasourceID,
		arg.Title,
		arg.Description,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DatasourceID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const newTextChunk = `-- name: NewTextChunk :one
INSERT INTO text_chunk (id, document_id, content)
VALUES (?, ?, ?)
RETURNING id, document_id, content, created_at
`

type NewTextChunkParams struct {
	ID         string
	DocumentID string
	Content    string
}

func (q *Queries) NewTextChunk(ctx context.Context, arg NewTextChunkParams) (TextChunk, error) {
	row := q.db.QueryRowContext(ctx, newTextChunk, arg.ID, arg.DocumentID, arg.Content)
	var i TextChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
