// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dao

import (
	"context"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE
FROM document
WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const deleteTextChunk = `-- name: DeleteTextChunk :exec
DELETE
FROM text_chunk
WHERE id = ?
`

func (q *Queries) DeleteTextChunk(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTextChunk, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, description, data, created_at
FROM document
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getTextChunk = `-- name: GetTextChunk :one
SELECT id, document_id, content, seg_content, created_at
FROM text_chunk
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTextChunk(ctx context.Context, id string) (TextChunk, error) {
	row := q.db.QueryRowContext(ctx, getTextChunk, id)
	var i TextChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.SegContent,
		&i.CreatedAt,
	)
	return i, err
}

const listTextChunksByDocumentID = `-- name: ListTextChunksByDocumentID :many
SELECT id, document_id, content, seg_content, created_at
FROM text_chunk
WHERE document_id = ?
`

func (q *Queries) ListTextChunksByDocumentID(ctx context.Context, documentID string) ([]TextChunk, error) {
	rows, err := q.db.QueryContext(ctx, listTextChunksByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TextChunk
	for rows.Next() {
		var i TextChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.SegContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newDocument = `-- name: NewDocument :exec
INSERT INTO document (id, title, description, data)
VALUES (?, ?, ?, ?)
`

type NewDocumentParams struct {
	ID          string
	Title       string
	Description string
	Data        string
}

func (q *Queries) NewDocument(ctx context.Context, arg NewDocumentParams) error {
	_, err := q.db.ExecContext(ctx, newDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Data,
	)
	return err
}

const newTextChunk = `-- name: NewTextChunk :one
INSERT INTO text_chunk (id, document_id, content, seg_content)
VALUES (?, ?, ?, ?)
RETURNING id, document_id, content, seg_content, created_at
`

type NewTextChunkParams struct {
	ID         string
	DocumentID string
	Content    string
	SegContent string
}

func (q *Queries) NewTextChunk(ctx context.Context, arg NewTextChunkParams) (TextChunk, error) {
	row := q.db.QueryRowContext(ctx, newTextChunk,
		arg.ID,
		arg.DocumentID,
		arg.Content,
		arg.SegContent,
	)
	var i TextChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.SegContent,
		&i.CreatedAt,
	)
	return i, err
}
