// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dao

import (
	"context"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE
FROM document
WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const deleteTextChunk = `-- name: DeleteTextChunk :exec
DELETE
FROM text_chunk
WHERE id = ?
`

func (q *Queries) DeleteTextChunk(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTextChunk, id)
	return err
}

const deleteTextChunkFTSByDocumentID = `-- name: DeleteTextChunkFTSByDocumentID :exec
DELETE
FROM text_chunk_fts
WHERE id IN (SELECT id
             FROM text_chunk tc
             WHERE tc.document_id = ?)
`

func (q *Queries) DeleteTextChunkFTSByDocumentID(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTextChunkFTSByDocumentID, documentID)
	return err
}

const deleteTextChunkFTSByID = `-- name: DeleteTextChunkFTSByID :exec
DELETE
FROM text_chunk_fts
WHERE id = ?
`

func (q *Queries) DeleteTextChunkFTSByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTextChunkFTSByID, id)
	return err
}

const deleteTextChunksByDocumentID = `-- name: DeleteTextChunksByDocumentID :exec
DELETE
FROM text_chunk
WHERE document_id = ?
`

func (q *Queries) DeleteTextChunksByDocumentID(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTextChunksByDocumentID, documentID)
	return err
}

const deleteTextEmbeddingsByDocumentID = `-- name: DeleteTextEmbeddingsByDocumentID :exec
DELETE
FROM text_embedding
WHERE text_chunk_id IN (SELECT id
                        FROM text_chunk tc
                        WHERE tc.document_id = ?)
`

func (q *Queries) DeleteTextEmbeddingsByDocumentID(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTextEmbeddingsByDocumentID, documentID)
	return err
}

const deleteTextEmbeddingsByTextChunkID = `-- name: DeleteTextEmbeddingsByTextChunkID :exec
DELETE
FROM text_embedding
WHERE text_chunk_id = ?
`

func (q *Queries) DeleteTextEmbeddingsByTextChunkID(ctx context.Context, textChunkID string) error {
	_, err := q.db.ExecContext(ctx, deleteTextEmbeddingsByTextChunkID, textChunkID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, description, data, created_at
FROM document
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getTextChunk = `-- name: GetTextChunk :one
SELECT id, document_id, content, seg_content, created_at
FROM text_chunk
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTextChunk(ctx context.Context, id string) (TextChunk, error) {
	row := q.db.QueryRowContext(ctx, getTextChunk, id)
	var i TextChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.SegContent,
		&i.CreatedAt,
	)
	return i, err
}

const insertTextChunkFTS = `-- name: InsertTextChunkFTS :exec
INSERT INTO text_chunk_fts (id, seg_content)
VALUES (?, ?)
`

type InsertTextChunkFTSParams struct {
	ID         string
	SegContent string
}

func (q *Queries) InsertTextChunkFTS(ctx context.Context, arg InsertTextChunkFTSParams) error {
	_, err := q.db.ExecContext(ctx, insertTextChunkFTS, arg.ID, arg.SegContent)
	return err
}

const listTextChunkIdByDocumentID = `-- name: ListTextChunkIdByDocumentID :many
SELECT id
FROM text_chunk
WHERE document_id = ?
`

func (q *Queries) ListTextChunkIdByDocumentID(ctx context.Context, documentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTextChunkIdByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextChunksByDocumentID = `-- name: ListTextChunksByDocumentID :many
SELECT id, document_id, content, seg_content, created_at
FROM text_chunk
WHERE document_id = ?
`

func (q *Queries) ListTextChunksByDocumentID(ctx context.Context, documentID string) ([]TextChunk, error) {
	rows, err := q.db.QueryContext(ctx, listTextChunksByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TextChunk
	for rows.Next() {
		var i TextChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.SegContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newDocument = `-- name: NewDocument :exec
INSERT INTO document (id, title, description, data)
VALUES (?, ?, ?, ?)
`

type NewDocumentParams struct {
	ID          string
	Title       string
	Description string
	Data        string
}

func (q *Queries) NewDocument(ctx context.Context, arg NewDocumentParams) error {
	_, err := q.db.ExecContext(ctx, newDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Data,
	)
	return err
}

const newTextChunk = `-- name: NewTextChunk :one
INSERT INTO text_chunk (id, document_id, content, seg_content)
VALUES (?, ?, ?, ?) RETURNING id, document_id, content, seg_content, created_at
`

type NewTextChunkParams struct {
	ID         string
	DocumentID string
	Content    string
	SegContent string
}

func (q *Queries) NewTextChunk(ctx context.Context, arg NewTextChunkParams) (TextChunk, error) {
	row := q.db.QueryRowContext(ctx, newTextChunk,
		arg.ID,
		arg.DocumentID,
		arg.Content,
		arg.SegContent,
	)
	var i TextChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.SegContent,
		&i.CreatedAt,
	)
	return i, err
}

const newTextEmbedding = `-- name: NewTextEmbedding :exec
INSERT INTO text_embedding (model_id, text_chunk_id, vector)
VALUES (?, ?, ?)
`

type NewTextEmbeddingParams struct {
	ModelID     string
	TextChunkID string
	Vector      []byte
}

func (q *Queries) NewTextEmbedding(ctx context.Context, arg NewTextEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, newTextEmbedding, arg.ModelID, arg.TextChunkID, arg.Vector)
	return err
}
